.travis.yml, rtlamr2mqtt.py, rtlamt2mqtt.yaml
=> Added trevis-ci

.travis.yml, Dockerfile, README.md, rtlamr2mqtt.py, rtlamt2mqtt.yaml
=> Fixed LISTEN mode

README.md, rtlamr2mqtt-addon/config.json, rtlamr2mqtt.py
=> Allow users to configure a state_class for their meter.

README.md
Documentation update to explain PR https://github.com/allangood/rtlamr2mqtt/pull/102
=> Document serial number rtl_tcp arguments in DEBUG mode

rtlamr2mqtt-addon/config.json
Added all supported architectures
=> Added all supported architectures

rtlamr2mqtt-addon/config.yaml, rtlamr2mqtt-addon/rtlamr2mqtt.py
This fix solves #141 
RTL_TCP keeps running after the kill call
=> Fix for #141

rtlamr2mqtt-addon/config.yaml, rtlamr2mqtt-addon/rtlamr2mqtt.py
=> Fix for #168

rtlamr2mqtt-addon/config.yaml
Added port to config options.
Fix for #159
=> Fix for #159

rtlamr2mqtt-addon/rtlamr2mqtt.py
=> Update rtlamr2mqtt.py (fix typo)

rtlamr2mqtt-addon/config.yaml
=> Bump version to fix #220

CHANGELOG.md, README.md, rtlamr2mqtt-addon/Dockerfile, rtlamr2mqtt-addon/app/helpers/config.py, rtlamr2mqtt-addon/app/helpers/ha_messages.py, rtlamr2mqtt-addon/app/rtlamr2mqtt.yaml, rtlamr2mqtt-addon/config.yaml
**Changes**
- Changed `README.md` file
- Changed `Changelog.md` file
- Removed i386, ARMv7 and ARMhf architectures
- Better meters config file handler
=> issue-193 Beter config file handler

.github/workflows/main.yml
Removed `linux/arm/v7` and `linux/arm/v6`
=> issue-193 Remove deprecated architectures

rtlamr2mqtt-addon/app/helpers/read_output.py
Add NetIDM LastConsumption message support
=> Add NetIDM LastConsumption message support

rtlamr2mqtt-addon/app/helpers/buildcmd.py, rtlamr2mqtt-addon/app/helpers/usb_utils.py, rtlamr2mqtt-addon/app/rtlamr2mqtt.py
#277
* Added `tickle_rtl_tcp` function to wake `rtl_tcp`
* Fixed logic when a RTL device is needed when a remote server is specified
=> 277 Fix hang rtl_tcp

rtlamr2mqtt-addon/DOCS.md, rtlamr2mqtt-addon/Dockerfile, rtlamr2mqtt-addon/app/helpers/config.py, rtlamr2mqtt-addon/app/helpers/info.py, rtlamr2mqtt-addon/app/rtlamr2mqtt.py, rtlamr2mqtt-addon/config.yaml
**Changes**
- Fixed `rtl_tcp` hanging forever
- Fixed logic to use remote `rtl_tcp`
- Added logic to get MQTT user and password from Mosquitto Add-On
=> 277 Fix hang issue in rtlamr2mqtt

CHANGELOG.md, rtlamr2mqtt-addon/app/rtlamr2mqtt.py
- Fixed remote `rtl_tcp`
- Added Changelog
=> 277 fix remote rtltcp

CHANGELOG.md, rtlamr2mqtt-addon/app/rtlamr2mqtt.py
* 277 Fix remote rtltcp
* Added CHANGELOG
=> 277 fix remote rtltcp (#286)

CHANGELOG.md, rtlamr2mqtt-addon/Dockerfile.mock, rtlamr2mqtt-addon/app/helpers/buildcmd.py, rtlamr2mqtt-addon/app/helpers/info.py, rtlamr2mqtt-addon/app/rtlamr2mqtt.py, rtlamr2mqtt-addon/config.yaml
**Changes**
- fix: Bug #288
- fix: Dockerfile.mock now works
=> 288 fix amr reading

CHANGELOG.md, rtlamr2mqtt-addon/Dockerfile.mock, rtlamr2mqtt-addon/app/helpers/buildcmd.py, rtlamr2mqtt-addon/app/helpers/info.py, rtlamr2mqtt-addon/app/rtlamr2mqtt.py, rtlamr2mqtt-addon/config.yaml
**Changes**
- fix: MQTT not receiving updates #288
- fix: Dockerfile.mock now works
- fix: Ignore USB lookup when a remote `rtl_tcp` is specified
- chore: Bump version
=> 288 New release 2025.6.3

CHANGELOG.md, rtlamr2mqtt-addon/DOCS.md, rtlamr2mqtt-addon/app/helpers/config.py, rtlamr2mqtt-addon/app/helpers/ha_messages.py, rtlamr2mqtt-addon/app/helpers/info.py, rtlamr2mqtt-addon/app/helpers/mqtt_client.py, rtlamr2mqtt-addon/app/rtlamr2mqtt.py, rtlamr2mqtt-addon/config.yaml
- Added support for non-blocking reads in the rtlamr2mqtt addon.
- Add Discover paylod re-publish messages logic
- Detect process termination and restart
=> 319 Non Blocking Readings

rtlamr2mqtt-addon/app/rtlamr2mqtt.py
#318 Wait for `sleep_for` seconds before restarting dead process
=> 318 Sleep for before restarting dead process
